# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Pricing"
url = "/pricing"
weight = 2

[[main]]
name = "Contact"
url = "/contact"
weight = 3

[[main]]
name = "FAQ"
url = "/faq"
weight = 4

# footer menu left
[[footer_left]]
name = "Get Started"
url = "https://app.hugity.com"

[[footer_left]]
name = "FAQ"
url = "/faq"

[[footer_left]]
name = "Pricing"
url = "/pricing"


# footer menu middle
[[footer_middle]]
name = ""
url = ""

# footer menu right
[[footer_right]]
name = ""
url = ""